package sit374_team17.propertyinspector.Note;

import android.os.Parcel;
import android.os.Parcelable;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "InspectionComments")
public class Note implements Parcelable {
    private String CommentID;
    private String CommentType;
    private String CommentTitle;
    private String Description;
    private String PropertyID;
    private String photo;

    public Note(){}

    public Note(String CommentID, String CommentType, String CommentTitle, String Description, String PropertyID, String photo){
        this.CommentID = CommentID;
        this.CommentType = CommentType;
        this.CommentTitle = CommentTitle;
        this.Description = Description;
        this.PropertyID = PropertyID;
        this.photo = photo;
    }


    @DynamoDBAttribute(attributeName = "CommentType")
    public String getCommentType() {
        return CommentType;
    }
    public void setCommentType(String commentType) {
        CommentType = commentType;
    }

    @DynamoDBAttribute(attributeName = "CommentTitle")
    public String getCommentTitle() {
        return CommentTitle;
    }

    public void setCommentTitle(String commentTitle) {
        CommentTitle = commentTitle;
    }

    @DynamoDBAttribute(attributeName = "Description")
    public String getDescription() {
        return Description;
    }

    public void setDescription(String description) {
        Description = description;
    }

    @DynamoDBHashKey(attributeName = "CommentID")
    @DynamoDBAutoGeneratedKey
    public String getCommentID() {
        return CommentID;
    }

    public void setCommentID(String commentID) {
        CommentID = commentID;
    }

    @DynamoDBAttribute(attributeName = "PropertyID")
    public String getPropertyId() {
        return PropertyID;
    }

    public void setPropertyId(String propertyId) {
        PropertyID = propertyId;
    }

    public void setPhoto(String photo) {this.photo = photo;}
    @DynamoDBAttribute(attributeName = "Title")
    public String getPhoto() {
        return photo;
    }


    protected Note(Parcel in) {
        CommentID = in.readString();
        CommentType = in.readString();
        CommentTitle = in.readString();
        Description = in.readString();
        PropertyID = in.readString();
        photo = in.readString();
    }

    @Override
    public void writeToParcel(Parcel dest, int flags) {
        dest.writeString(CommentID);
        dest.writeString(CommentType);
        dest.writeString(CommentTitle);
        dest.writeString(Description);
        dest.writeString(PropertyID);
        dest.writeString(photo);
    }

    @Override
    public int describeContents() {
        return 0;
    }

    public static final Creator<Note> CREATOR = new Creator<Note>() {
        @Override
        public Note createFromParcel(Parcel in) {
            return new Note(in);
        }

        @Override
        public Note[] newArray(int size) {
            return new Note[size];
        }
    };
}
