package sit374_team17.propertyinspector.Note;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;

@DynamoDBTable(tableName = "InspectionComments")
public class Note {
    private String CommentID;
    private String CommentType;
    private String Description;
    private String PropertyID;

    @DynamoDBAttribute(attributeName = "CommentType")
    public String getCommentType() {
        return CommentType;
    }
    public void setCommentType(String commentType) {
        CommentType = commentType;
    }

    @DynamoDBAttribute(attributeName = "Description")
    public String getDescription() {
        return Description;
    }
    public void setDescription(String description) {
        Description = description;
    }

    @DynamoDBHashKey(attributeName = "CommentID")
    @DynamoDBAutoGeneratedKey
    public String getCommentID() {     return CommentID;  }
    public void setCommentID(String commentID) {
        CommentID = commentID;
    }


    @DynamoDBAttribute(attributeName = "PropertyID")
    public String getPropertyId() {  return PropertyID;  }
    public void setPropertyId(String propertyId) {
        PropertyID = propertyId;
    }


}
